// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIRE_BASE_API_KEY']!,
    appId: dotenv.env['FIRE_BASE_APP_ID']!,
    messagingSenderId: dotenv.env['FIRE_BASE_SENDER_ID']!,
    projectId: dotenv.env['FIRE_BASE_PROJECT_ID']!,
    authDomain: dotenv.env['FIRE_BASE_AUTH_DOMAIN']!,
    storageBucket: dotenv.env['FIRE_BASE_STORAGE_BUCKET']!,
    measurementId: dotenv.env['FIRE_BASE_MEASUREMENT_ID']!,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRC3jsntlmSDL4ImC1xziD-My3pODrIeA',
    appId: '1:972120897822:android:d4ab6af25b357dcd8a710f',
    messagingSenderId: '972120897822',
    projectId: 'addis-inforamtion-highway',
    storageBucket: 'addis-inforamtion-highway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhO7bf-LscqJ-JiVrRXN4T0XBVgIZvVU',
    appId: '1:972120897822:ios:1c81eddfb9a3d8808a710f',
    messagingSenderId: '972120897822',
    projectId: 'addis-inforamtion-highway',
    storageBucket: 'addis-inforamtion-highway.firebasestorage.app',
    iosBundleId: 'com.example.addisInformationHighwayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvhO7bf-LscqJ-JiVrRXN4T0XBVgIZvVU',
    appId: '1:972120897822:ios:69da7d8f70e3a2f28a710f',
    messagingSenderId: '972120897822',
    projectId: 'addis-inforamtion-highway',
    storageBucket: 'addis-inforamtion-highway.firebasestorage.app',
    iosBundleId: 'com.example.addisInforamtionHighwayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYpgo2vzv3W8raOqskOMfL1PVrIMUW9-U',
    appId: '1:972120897822:web:3fb7841ff0368e218a710f',
    messagingSenderId: '972120897822',
    projectId: 'addis-inforamtion-highway',
    authDomain: 'addis-inforamtion-highway.firebaseapp.com',
    storageBucket: 'addis-inforamtion-highway.firebasestorage.app',
    measurementId: 'G-ZT2YM578ND',
  );
}
